# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "protobuf-dynamicTyping" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['1.1', '2.0', '4.5', '5.0' ]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: cd ${{ github.workspace }} && dotnet restore ./csharp/src/Google.Protobuf.sln
    - name: Build
      run: cd ${{ github.workspace }} && dotnet build ./csharp/src/Google.Protobuf.sln --no-restore
    - name: Test
      run: cd ${{ github.workspace }} && dotnet test ./csharp/src/Google.Protobuf.sln --no-build --verbosity normal